### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by MentalGear** [mkaemmerer/filter-effects#6]
Hi @mkaemmerer ,
Thanks for this great package. I want to install this via npm, is it the same as [npm package](https://www.npmjs.com/package/@mattsnax/filter-effects) which however is tagged at v.0.9 ?

**Comment by mkaemmerer** [comment]
Yep, it is the same package. I've been somewhat lax in maintaining this repo, but I've got some time today to take care of some things, including updating the tags on Github.

**Comment by MentalGear** [comment]
You might want to double-check the npm version. I think I wasnt able to use it, as it was linking to a none existing /dist/ folder.
